id: A105CE1A9
title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:23:22.574060
  last_modified_at: 2022-03-01 02:23:22.574068
